algoritmo "AreaPerimetroRetangulo"
// Função: determinar a area e o perimetro de um retangulo
// Autor: Jennifer Pereira Maria
// Professor: Cintia Pinho
// Data: 03/05/2020
// Seção de Declarações 
var

a,p,b,al: real

inicio
//entrada
escreval ("Digite a Altura")
leia (al)
escreval ("Digite a Base")
leia (b)

//Processamento
a <- b*al

p <- ((b*2)+(al*2))

//saida
escreval("A area do Retangulo é:",a)

escreval("O perimetro do Retangulo é:",p)

fimalgoritmo
