algoritmo "dolar"
// Função :converter o dolar
// Autor :jennifer pereira maria
// Data : 18/05/2020
// Seção de Declarações 
var
cot, valor, r: real

inicio
// entrada

escreval("Escreva o valor da cotação do dolar")
leia(cot)
escreval("Quanto quer converter?")
leia(valor)

// processamento

r<- valor/cot

// saida

escreval(valor, " reais e o mesmo que", r,  "dolares")



fimalgoritmo
