algoritmo "blitz3"
// Função :
// Autor :  Jennifer Pereira maria
// Data : 23/06/2020
// Seção de Declarações 
var
idade: inteiro
resp: caracter

inicio
//entrada

escreval ("Qual é sua idade?")
leia (idade)

escreval ("Tem Habilitacao?")
leia (resp)

//decisao

se ((idade>=18) e (resp="sim")) entao
         escreval ("Pode passar!!")
senao
         escreval ("Não pode passar!!")
fimse


fimalgoritmo
